http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api-admin:
    host: localhost
    paths: "/api/admin/*"
  api-auth:
    host: localhost
    paths: "/api/auth/*"
  api-user:
    host: localhost
    paths: "/api/user/*"
  api-mail:
    host: localhost
    paths: "/api/mail/*"
serviceEndpoints:
  auth:
    url: "http://localhost:3001"
  user:
    url: "http://localhost:3002"
  admin:
    url: "http://localhost:3003"
  mail:
    url: "http://localhost:3004"
policies:
  - log
  - proxy
  - jwt
  - request-transformer
pipelines:
  auth-pipe:
    apiEndpoints:
      - api-auth
    policies:
      - log:
          action:
            message: "auth ${req.method}"
      - proxy:
          - action:
              serviceEndpoint: auth
              changeOrigin: true

  user-pipe:
    apiEndpoints:
      - api-user
    policies:
      - log:
          action:
            message: "user ${req.method}"
      - jwt:
          action:
            secretOrPublicKey: "smilegate_stove_jjang_jae_meet_dda"
            checkCredentialExistence: false
      - proxy:
          - action:
              serviceEndpoint: user
              changeOrigin: true

  admin-pipe:
    apiEndpoints:
      - api-admin
    policies:
      - log:
          action:
            message: "admin ${req.method}"
      - jwt:
          action:
            secretOrPublicKey: "smilegate_stove_jjang_jae_meet_dda"
            checkCredentialExistence: false
      - proxy:
          - action:
              serviceEndpoint: admin
              changeOrigin: true

  mail-pipe:
    apiEndpoints:
      - api-mail
    policies:
      - log:
          action:
            message: "mail ${req.method}"
      - proxy:
          - action:
              serviceEndpoint: mail
              changeOrigin: true
